Microservice.Web.Frontend/Microservice.Web.Frontend/Models/Dtos/ResultDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Microservice.Web.Frontend.Models.Dtos
{
    public class ResultDto
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
    }

    public class ResultDto<T>
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
        public T Data { get; set; }

    }

}

Microservice.Web.Frontend/Microservice.Web.Frontend/Models/ErrorViewModel.cs
using System;

namespace Microservice.Web.Frontend.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Microservice.Web.Frontend/Microservice.Web.Frontend/Controllers/BasketController.cs
using Microservice.Web.Frontend.Models.Dtos;
using Microservice.Web.Frontend.Servcies.BasketService;
using Microservice.Web.Frontend.Servcies.DiscountServices;
using Microservice.Web.Frontend.Servcies.ProductServices;
using Microsoft.AspNetCore.Mvc;

namespace Microservice.Web.Frontend.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketService basketService;
        private readonly IProductService productService;
        private readonly IDiscountService discountService;
        private readonly string UserId = "1";
        public BasketController(IBasketService basketService,
            IProductService productService,
            IDiscountService discountService)
        {
            this.basketService = basketService;
            this.productService = productService;
            this.discountService = discountService;
        }
        public IActionResult Index()
        {
            var basket = basketService.GetBasket(UserId);

            if (basket.discountId.HasValue)
            {
                var discount = discountService.GetDiscountById(basket.discountId.Value);
                basket.DiscountDetail = new DiscountInBasketDto
                {
                    Amount = discount.Data.Amount,
                    DiscountCode = discount.Data.Code,
                };
            }

            return View(basket);
        }

        public IActionResult Delete(Guid Id)
        {
            basketService.DeleteFromBasket(Id);
            return RedirectToAction("Index");
        }

        public IActionResult AddToBasket(Guid ProductId)
        {
            var product = productService.Getproduct(ProductId);
            var basket = basketService.GetBasket(UserId);

            AddToBasketDto item = new AddToBasketDto()
            {
                BasketId = basket.id,
                ImageUrl = product.image,
                ProductId = product.id,
                ProductName = product.name,
                Quantity = 1,
                UnitPrice = product.price,
            };
            basketService.AddToBasket(item, UserId);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(Guid BasketItemId, int quantity)
        {
            basketService.UpdateQuantity(BasketItemId, quantity);
            return RedirectToAction("Index");

        }




        [HttpPost]
        public IActionResult ApplyDiscount(string DiscountCode)
        {
            if (string.IsNullOrWhiteSpace(DiscountCode))
            {
                return Json(new ResultDto
                {
                    IsSuccess = false,
                    Message = "لطفا کد تخفیف را وارد نمایید"
                });
            }
            var discount = discountService.GetDiscountByCode(DiscountCode);
            if (discount.IsSuccess == true)
            {
                if (discount.Data.Used)
                {
                    return Json(new ResultDto
                    {
                        IsSuccess = false,
                        Message = "این کد تخفیف قبلا استفاده شده است"
                    });
                }

                var basket = basketService.GetBasket(UserId);
                basketService.ApplyDiscountToBasket(Guid.Parse(basket.id), discount.Data.Id);
                discountService.UseDiscount(discount.Data.Id);
                return Json(new ResultDto
                {
                    IsSuccess = true,
                    Message = "کد تخفیف با موفقیت به سبد خرید شما اعمال شد",
                });
            }
            else
            {
                return Json(new ResultDto
                {
                    IsSuccess = false,
                    Message = discount.Message,
                });
            }
        }
    }


}

Microservice.Web.Frontend/Microservice.Web.Frontend/Controllers/HomeController.cs
using Microservice.Web.Frontend.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Microservice.Web.Frontend.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Microservice.Web.Frontend/Microservice.Web.Frontend/Controllers/ProductController.cs
using Microservice.Web.Frontend.Servcies.ProductServices;
using Microsoft.AspNetCore.Mvc;

namespace Microservice.Web.Frontend.Controllers
{
	public class ProductController : Controller
	{
		private readonly IProductService _productService;

		public ProductController(IProductService productService)
		{
			_productService = productService;
		}

		public IActionResult Index()
		{
			var product=_productService.GetAllProduct();
			return View(product);
		}
        public IActionResult Details(Guid id)
        {
            var product = _productService.Getproduct(id);
            return View(product);
        }
    }
}

Microservice.Web.Frontend/Microservice.Web.Frontend/Views/Basket/Index.cshtml
@model Microservice.Web.Frontend.Servcies.BasketService.BasketDto

@{
    ViewData["Title"] = "سبد خرید";
}
<h1>سبد خرید</h1>

<div class="row text-right">
    <table class="table col-md-9">
        <thead>
            <tr>

                <th>
                    <label asp-for="items.FirstOrDefault().productName"></label>
                </th>
                <th>
                    <label asp-for="items.FirstOrDefault().unitPrice"></label>
                </th>
                <th>
                    <label asp-for="items.FirstOrDefault().quantity"></label>
                </th>
                <th>
                    <label>قیمت کل</label>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.items)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.productName)
                    </td>
                    <td>
                        <b class="text-success">@item.unitPrice.ToString("n0")  تومان</b>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.quantity)
                    </td>
                    <td>
                        <b class="text-success">@item.TotalPrice().ToString("n0")  تومان</b>
                    </td>
                    <td class="row">
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Basket" asp-route-id="@item.id"> حذف</a>
                        <a class="btn btn-warning" onclick="ShowEdit('@item.id','@item.quantity')">ویزایش تعداد</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr class="bg-dark text-white">

                <td>
                    قیمت کل
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                    <b>@Model.TotalPrice().ToString("n0")  تومان</b>
                </td>
                <td>
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="col-md-3 card">
        <div class="row col-md-12 card-body ">
            <label>استفاده از کد تخفیف</label>
            <input type="text" class="form-control col-md-12" id="txtDiscountCode" placeholder="کد تخفیف را وارد نمایید" />
            <button type="submit" onclick="ApplyDiscountCode()" id="btnApplyDiscountCode" class="btn btn-warning btn-sm col-md-12">اعمال کد تخفیف</button>


            <hr />
            @if (Model.DiscountDetail != null)
            {
                <div>
                    <b> کد تخفیف استفاده شده :</b>
                    <small>  @Model.DiscountDetail.DiscountCode</small>

                    <b class="col-md-12">مبلغ : @Model.DiscountDetail.Amount.ToString("n0")  تومان</b>
                </div>

            }

        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="editQuantityModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-action="Edit" asp-controller="Basket">
                <div class="modal-body">
                    <input type="hidden" id="BasketItemId" name="BasketItemId" value="" />
                    <input type="number" id="quantity" name="quantity" value="" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">برگشت</button>
                    <button type="submit" class="btn btn-primary">ثبت تغییرات</button>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts
{
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script>

        function ShowEdit(BasketItemId, quantity) {
            $("#BasketItemId").val(BasketItemId);
            $("#quantity").val(quantity);
            $("#editQuantityModal").modal({
                fadeDuration: 400,
                fadeDelay: 0.10
            });
        }

        function ApplyDiscountCode() {

            var code = $("#txtDiscountCode").val();

            var postData = { 'DiscountCode': code };

            $.ajax({
                contentType: 'application/x-www-form-urlencoded',
                dataType: 'json',
                type: "POST",
                url: "Basket/ApplyDiscount",
                data: postData,
                success: function (data) {
                    if (data.isSuccess) {
                        swal({
                            title: "بسیار خوب!",
                            text: data.message,
                            icon: "warning",
                            button: "خب",
                        });
                    }
                    else {
                        swal({
                            title: "هشدار!",
                            text: data.message,
                            icon: "warning",
                            button: "خب",
                        });
                    }
                }
            });
        }

    </script>


}

Microservice.Web.Frontend/Microservice.Web.Frontend/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Microservice.Web.Frontend/Microservice.Web.Frontend/Views/Product/Details.cshtml
@model Microservice.Web.Frontend.Servcies.ProductServices.ProductDto

@{
    ViewData["Title"] = Model.name ;
}

<h1>@Model.name</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
    </dl>
</div>
<div>
     <a asp-action="Index">Back to List</a>
</div>

Microservice.Web.Frontend/Microservice.Web.Frontend/Views/Product/Index.cshtml
@model IEnumerable<Microservice.Web.Frontend.Servcies.ProductServices.ProductDto>

@{
    ViewData["Title"] = "محصولات";
}

<h1>محصولات </h1>

 
<table class="table table-hover table-bordered table-responsive" >
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @item.price.ToString("n0") تومان
            </td>
            <td>
                <a asp-action="Details"
                   asp-controller="Product"
                   asp-route-id="@item.id">
                    جزئیات
                </a>
                    <a asp-controller="Basket"  asp-action="AddToBasket" asp-route-ProductId="@item.id" class="btn btn-success"> افزودن به سبد </a>

            </td>
        </tr>
}
    </tbody>
</table>

Microservice.Web.Frontend/Microservice.Web.Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="text-right" style="direction:rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Microservices.Web.Frontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">پروژه  میکروسرویس</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">محصولات</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="basket" asp-action="Index">سبد خرید</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">درباره ما</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Microservices.Web.Frontend - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>